DROP TABLE `accessibilities`;--> statement-breakpoint
DROP TABLE `adept_access`;--> statement-breakpoint
DROP TABLE `airtime_providers`;--> statement-breakpoint
DROP TABLE `airtime_transactions`;--> statement-breakpoint
DROP TABLE `app_settings`;--> statement-breakpoint
DROP TABLE `banks`;--> statement-breakpoint
DROP TABLE `beneficiaries`;--> statement-breakpoint
DROP TABLE `bill_mates_favourites`;--> statement-breakpoint
DROP TABLE `bill_mates_transactions`;--> statement-breakpoint
DROP TABLE `blue_admin_roles`;--> statement-breakpoint
DROP TABLE `blue_admins`;--> statement-breakpoint
DROP TABLE `business_airtime_transactions`;--> statement-breakpoint
DROP TABLE `business_branches`;--> statement-breakpoint
DROP TABLE `business_categories`;--> statement-breakpoint
DROP TABLE `business_data_transactions`;--> statement-breakpoint
DROP TABLE `business_devices`;--> statement-breakpoint
DROP TABLE `business_fees`;--> statement-breakpoint
DROP TABLE `business_onboarding_forms`;--> statement-breakpoint
DROP TABLE `business_payment_transactions`;--> statement-breakpoint
DROP TABLE `business_pins`;--> statement-breakpoint
DROP TABLE `business_power_transactions`;--> statement-breakpoint
DROP TABLE `business_profiles`;--> statement-breakpoint
DROP TABLE `business_recovery_infos`;--> statement-breakpoint
DROP TABLE `business_security_questions`;--> statement-breakpoint
DROP TABLE `business_settlement_accounts`;--> statement-breakpoint
DROP TABLE `business_shareholders`;--> statement-breakpoint
DROP TABLE `business_transaction_histories`;--> statement-breakpoint
DROP TABLE `business_tv_transactions`;--> statement-breakpoint
DROP TABLE `business_users`;--> statement-breakpoint
DROP TABLE `business_wallet_accounts`;--> statement-breakpoint
DROP TABLE `business_wallet_snapshots`;--> statement-breakpoint
DROP TABLE `business_wallets`;--> statement-breakpoint
DROP TABLE `dashme_idempotency_records`;--> statement-breakpoint
DROP TABLE `dashme_transactions`;--> statement-breakpoint
DROP TABLE `dashme_transactions_attempt_logs`;--> statement-breakpoint
DROP TABLE `data_packages`;--> statement-breakpoint
DROP TABLE `data_providers`;--> statement-breakpoint
DROP TABLE `data_transactions`;--> statement-breakpoint
DROP TABLE `deleted_accounts`;--> statement-breakpoint
DROP TABLE `document_types`;--> statement-breakpoint
DROP TABLE `flagged_users`;--> statement-breakpoint
DROP TABLE `irchg_banks`;--> statement-breakpoint
DROP TABLE `irecharge_data_packages`;--> statement-breakpoint
DROP TABLE `irecharge_power_providers`;--> statement-breakpoint
DROP TABLE `irecharge_tv_packages`;--> statement-breakpoint
DROP TABLE `kycs`;--> statement-breakpoint
DROP TABLE `migrations`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `otps`;--> statement-breakpoint
DROP TABLE `payment_links`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `paystack_banks`;--> statement-breakpoint
DROP TABLE `pilot_testers`;--> statement-breakpoint
DROP TABLE `pins`;--> statement-breakpoint
DROP TABLE `power_providers`;--> statement-breakpoint
DROP TABLE `power_transactions`;--> statement-breakpoint
DROP TABLE `reasons`;--> statement-breakpoint
DROP TABLE `recovery_infos`;--> statement-breakpoint
DROP TABLE `report_preferences`;--> statement-breakpoint
DROP TABLE `security_questions`;--> statement-breakpoint
DROP TABLE `sms_logs`;--> statement-breakpoint
DROP TABLE `staff_profiles`;--> statement-breakpoint
DROP TABLE `staff_roles`;--> statement-breakpoint
DROP TABLE `temp_accounts`;--> statement-breakpoint
DROP TABLE `temp_recovery_phones`;--> statement-breakpoint
DROP TABLE `transaction_histories`;--> statement-breakpoint
DROP TABLE `transactions`;--> statement-breakpoint
DROP TABLE `tv_packages`;--> statement-breakpoint
DROP TABLE `tv_providers`;--> statement-breakpoint
DROP TABLE `tv_transactions`;--> statement-breakpoint
DROP TABLE `user_accounts`;--> statement-breakpoint
DROP TABLE `user_card_details`;--> statement-breakpoint
DROP TABLE `user_tokens`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `ussd_withdrawals`;--> statement-breakpoint
DROP TABLE `wallet_accounts`;--> statement-breakpoint
DROP TABLE `wallet_snapshots`;--> statement-breakpoint
DROP TABLE `wallets`;--> statement-breakpoint
DROP TABLE `withdraw_credentials`;--> statement-breakpoint
DROP TABLE `withdraw_idempotency_records`;